// Sample data — editorial, intentional
const BOOKS = [
  { id: 1, title: 'Piranesi', author: 'Susanna Clarke', prog: 0.72, hue: 28, tone: 'warm', year: 2020,
    pages: 272, currentPage: 196, started: 'April 2', genre: 'Literary fiction', publisher: 'Bloomsbury',
    rating: 4.5, quote: 'The Beauty of the House is immeasurable; its Kindness infinite.',
    note: 'A quiet labyrinth of a novel. I keep returning to the tides.' },
  { id: 2, title: 'A Gentleman in Moscow', author: 'Amor Towles', prog: 0.35, hue: 12, tone: 'deep', year: 2016,
    pages: 462, currentPage: 162, started: 'March 21', genre: 'Historical fiction', publisher: 'Viking',
    rating: 4.0, quote: 'If a man does not master his circumstances then he is bound to be mastered by them.',
    note: 'The Count is turning out to be excellent company.' },
  { id: 3, title: 'The Overstory', author: 'Richard Powers', prog: 1.00, hue: 120, tone: 'forest', year: 2018,
    pages: 512, currentPage: 512, started: 'January 8', finished: 'February 24', genre: 'Eco-fiction',
    publisher: 'W. W. Norton', rating: 5.0,
    quote: 'The best arguments in the world won\u2019t change a person\u2019s mind. The only thing that can do that is a good story.',
    note: 'Changed how I see trees on my morning walk.' },
  { id: 4, title: 'Station Eleven', author: 'Emily St. John Mandel', prog: 0.55, hue: 210, tone: 'cold', year: 2014,
    pages: 333, currentPage: 183, started: 'April 9', genre: 'Speculative fiction', publisher: 'Knopf',
    rating: 4.5, quote: 'Survival is insufficient.', note: '' },
  { id: 5, title: 'Pachinko', author: 'Min Jin Lee', prog: 1.00, hue: 18, tone: 'warm', year: 2017,
    pages: 496, currentPage: 496, started: 'November 2025', finished: 'December 18, 2025', genre: 'Historical fiction',
    publisher: 'Grand Central', rating: 5.0,
    quote: 'History has failed us, but no matter.', note: 'A saga that earns every page.' },
  { id: 6, title: 'Tomorrow, and Tomorrow, and Tomorrow', author: 'Gabrielle Zevin', prog: 0.18, hue: 265, tone: 'plum', year: 2022,
    pages: 416, currentPage: 75, started: 'April 14', genre: 'Literary fiction', publisher: 'Knopf',
    rating: 4.0, quote: 'What is a game? It\u2019s tomorrow, and tomorrow, and tomorrow.', note: '' },
  { id: 7, title: 'The Remains of the Day', author: 'Kazuo Ishiguro', prog: 1.00, hue: 38, tone: 'warm', year: 1989,
    pages: 258, currentPage: 258, started: 'October 2025', finished: 'October 30, 2025', genre: 'Literary fiction',
    publisher: 'Faber & Faber', rating: 5.0,
    quote: 'What can we ever gain in forever looking back and blaming ourselves?', note: 'Dignity as a quiet cathedral.' },
  { id: 8, title: 'Cloud Cuckoo Land', author: 'Anthony Doerr', prog: 0.08, hue: 195, tone: 'sky', year: 2021,
    pages: 640, currentPage: 51, started: 'April 15', genre: 'Literary fiction', publisher: 'Scribner',
    rating: 3.5, quote: '', note: 'Three timelines, one thread. Let\u2019s see.' },
  { id: 9, title: 'The Sympathizer', author: 'Viet Thanh Nguyen', prog: 0.00, hue: 5, tone: 'deep', year: 2015,
    pages: 384, currentPage: 0, genre: 'Literary fiction', publisher: 'Grove Press',
    rating: 0, quote: '', note: 'Recommended by J. Queued for May.' },
];

const FILMS = [
  { id: 1, title: 'La Chimera', director: 'Alice Rohrwacher', year: 2023, rating: 4.5, hue: 22, watched: true,
    runtime: 133, country: 'Italy', language: 'Italian', watchedOn: 'April 15, 2026', venue: 'At home',
    cast: ['Josh O\u2019Connor', 'Carol Duarte', 'Isabella Rossellini'],
    cinematographer: 'H\u00e9l\u00e8ne Louvart', composer: 'Vari',
    tagline: 'A dowser of the forgotten.',
    thought: 'Rohrwacher films time like a weathered fresco. Spellbound.' },
  { id: 2, title: 'Perfect Days', director: 'Wim Wenders', year: 2023, rating: 5.0, hue: 190, watched: true,
    runtime: 124, country: 'Japan', language: 'Japanese', watchedOn: 'April 8, 2026', venue: 'Cin\u00e9ma Verdi',
    cast: ['K\u014dji Yakusho', 'Tokio Emoto', 'Arisa Nakano'],
    cinematographer: 'Franz Lustig', composer: 'Various',
    tagline: 'Sunlight through branches. Again.',
    thought: 'A film that teaches you how to pay attention.' },
  { id: 3, title: 'Past Lives', director: 'Celine Song', year: 2023, rating: 4.5, hue: 10, watched: true,
    runtime: 105, country: 'USA / South Korea', language: 'English, Korean', watchedOn: 'March 29, 2026', venue: 'At home',
    cast: ['Greta Lee', 'Teo Yoo', 'John Magaro'],
    cinematographer: 'Shabier Kirchner', composer: 'Christopher Bear, Daniel Rossen',
    tagline: 'In-yun.',
    thought: 'The final walk is a decade of ache compressed into four minutes.' },
  { id: 4, title: 'Aftersun', director: 'Charlotte Wells', year: 2022, rating: 5.0, hue: 30, watched: true,
    runtime: 102, country: 'UK', language: 'English', watchedOn: 'March 12, 2026', venue: 'At home',
    cast: ['Paul Mescal', 'Frankie Corio', 'Celia Rowlson-Hall'],
    cinematographer: 'Gregory Oke', composer: 'Oliver Coates',
    tagline: 'A father, a daughter, a camcorder.',
    thought: 'A grief-dream. I have thought about it every week since.' },
  { id: 5, title: 'The Zone of Interest', director: 'Jonathan Glazer', year: 2023, rating: 4.0, hue: 85, watched: true,
    runtime: 105, country: 'UK / Poland', language: 'German', watchedOn: 'March 6, 2026', venue: 'Golem',
    cast: ['Christian Friedel', 'Sandra H\u00fcller'],
    cinematographer: '\u0141ukasz \u017bal', composer: 'Mica Levi',
    tagline: 'A garden. A wall. A sound.',
    thought: 'Sound design as moral architecture.' },
  { id: 6, title: 'Anatomy of a Fall', director: 'Justine Triet', year: 2023, rating: 4.5, hue: 210, watched: true,
    runtime: 150, country: 'France', language: 'French, English', watchedOn: 'February 22, 2026', venue: 'At home',
    cast: ['Sandra H\u00fcller', 'Swann Arlaud', 'Milo Machado Graner'],
    cinematographer: 'Simon Beaufils', composer: 'Various',
    tagline: 'Truth is a performance.',
    thought: 'The dog steals it.' },
  { id: 7, title: 'Drive My Car', director: 'Ry\u016bsuke Hamaguchi', year: 2021, rating: 5.0, hue: 0, watched: true,
    runtime: 179, country: 'Japan', language: 'Japanese', watchedOn: 'February 14, 2026', venue: 'At home',
    cast: ['Hidetoshi Nishijima', 'T\u014dko Miura', 'Masaki Okada'],
    cinematographer: 'Hidetoshi Shinomiya', composer: 'Eiko Ishibashi',
    tagline: 'We must keep on living.',
    thought: 'Patience rewarded; the cassette becomes a confession.' },
  { id: 8, title: 'The Worst Person in the World', director: 'Joachim Trier', year: 2021, rating: 4.5, hue: 340, watched: true,
    runtime: 128, country: 'Norway', language: 'Norwegian', watchedOn: 'January 31, 2026', venue: 'At home',
    cast: ['Renate Reinsve', 'Anders Danielsen Lie', 'Herbert Nordrum'],
    cinematographer: 'Kasper Tuxen', composer: 'Ola Fl\u00f8ttum',
    tagline: 'Twelve chapters of a life in motion.',
    thought: 'The frozen-time sequence is pure cinema.' },
  { id: 9, title: 'Petite Maman', director: 'C\u00e9line Sciamma', year: 2021, rating: 4.0, hue: 140, watched: true,
    runtime: 72, country: 'France', language: 'French', watchedOn: 'January 18, 2026', venue: 'At home',
    cast: ['Jos\u00e9phine Sanz', 'Gabrielle Sanz', 'Nina Meurisse'],
    cinematographer: 'Claire Mathon', composer: 'Para One',
    tagline: 'A forest, a girl, her mother as a child.',
    thought: 'A small miracle, 72 minutes long.' },
];

const HABITS = [
  { id: 1, label: 'Read 30 minutes',        streak: 47, cadence: 'Daily',    note: 'Morning, before coffee' },
  { id: 2, label: 'Write morning pages',    streak: 12, cadence: 'Daily',    note: 'Three pages, longhand' },
  { id: 3, label: 'Walk without a podcast', streak: 23, cadence: 'Daily',    note: 'Attention training' },
  { id: 4, label: 'Watch one film',         streak:  5, cadence: 'Weekly',   note: 'Sunday evening ritual' },
  { id: 5, label: 'Letter to a friend',     streak:  3, cadence: 'Weekly',   note: 'Handwritten, mailed' },
  { id: 6, label: 'No screens after 9pm',   streak: 18, cadence: 'Daily',    note: '' },
];

window.BOOKS = BOOKS;
window.FILMS = FILMS;
window.HABITS = HABITS;
